#!/usr/bin/env python3
"""
Init Command - Initialize a new MCP server project
"""

import os
import json
from pathlib import Path
from argparse import Namespace

from mcpforge.utils.formatting import print_success, print_error, print_info
from mcpforge.utils.colors import Colors


# Template for Python MCP server
PYTHON_TEMPLATE = '''#!/usr/bin/env python3
"""
{name} - MCP Server
Generated by MCPForge
"""

from mcp.server import Server
from mcp.types import TextContent

# Initialize server
server = Server("{name}")


@server.tool()
def example_tool(message: str) -> str:
    """
    An example tool that processes a message.
    
    Args:
        message: The input message to process
        
    Returns:
        Processed message
    """
    return f"Processed: {{message}}"


@server.resource("greeting://{{name}}")
def greeting_resource(name: str) -> str:
    """
    A greeting resource.
    
    Args:
        name: Name to greet
        
    Returns:
        Greeting message
    """
    return f"Hello, {{name}}!"


@server.prompt()
def example_prompt() -> str:
    """
    An example prompt template.
    """
    return "This is an example prompt."


if __name__ == "__main__":
    server.run()
'''


PYTHON_REQUIREMENTS = '''mcp>=1.0.0
'''


PYTHON_PYPROJECT = '''[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{name}"
version = "0.1.0"
description = "MCP Server - {name}"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["mcp", "model-context-protocol"]
authors = [
    {{ name = "Your Name", email = "your.email@example.com" }}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "mcp>=1.0.0",
]

[project.scripts]
{name} = "{module_name}.server:main"
'''


TYPESCRIPT_TEMPLATE = '''#!/usr/bin/env node
/**
 * {name} - MCP Server
 * Generated by MCPForge
 */

import {{ Server }} from "@modelcontextprotocol/sdk/server/index.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";
import {{
  CallToolRequestSchema,
  ListToolsRequestSchema,
}} from "@modelcontextprotocol/sdk/types.js";

// Initialize server
const server = new Server(
  {{
    name: "{name}",
    version: "0.1.0",
  }},
  {{
    capabilities: {{
      tools: {{}},
    }},
  }}
);

// List available tools
server.setRequestHandler(ListToolsRequestSchema, async () => {{
  return {{
    tools: [
      {{
        name: "example_tool",
        description: "An example tool",
        inputSchema: {{
          type: "object",
          properties: {{
            message: {{
              type: "string",
              description: "Message to process",
            }},
          }},
          required: ["message"],
        }},
      }},
    ],
  }};
}});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {{
  if (request.params.name === "example_tool") {{
    const {{ message }} = request.params.arguments as {{ message: string }};
    return {{
      content: [
        {{
          type: "text",
          text: `Processed: ${{message}}`,
        }},
      ],
    }};
  }}
  throw new Error(`Unknown tool: ${{request.params.name}}`);
}});

// Start server
async function main() {{
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("{name} MCP server running on stdio");
}}

main().catch(console.error);
'''


TYPESCRIPT_PACKAGE_JSON = '''{{
  "name": "{name}",
  "version": "0.1.0",
  "description": "MCP Server - {name}",
  "license": "MIT",
  "type": "module",
  "bin": {{
    "{name}": "./dist/index.js"
  }},
  "scripts": {{
    "build": "tsc",
    "start": "node dist/index.js",
    "dev": "tsc --watch"
  }},
  "dependencies": {{
    "@modelcontextprotocol/sdk": "^1.0.0"
  }},
  "devDependencies": {{
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }}
}}
'''


TYPESCRIPT_CONFIG = '''{{
  "compilerOptions": {{
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "Node16",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true
  }},
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}}
'''


def execute(args: Namespace) -> int:
    """Execute the init command."""
    name = args.name
    template = args.template
    path = args.path
    
    if not name:
        name = input("Project name: ").strip()
        if not name:
            print_error("Project name is required")
            return 1
    
    # Create project directory
    project_path = Path(path) / name if path != "." else Path(name)
    
    if project_path.exists():
        print_error(f"Directory {project_path} already exists")
        return 1
    
    project_path.mkdir(parents=True)
    print_info(f"Creating new MCP server project: {name}")
    print_info(f"Template: {template}")
    print_info(f"Location: {project_path.absolute()}")
    
    # Generate project based on template
    if template == "python":
        return generate_python_project(project_path, name)
    elif template in ["typescript", "javascript"]:
        return generate_typescript_project(project_path, name)
    else:
        print_error(f"Template '{template}' not yet implemented")
        return 1


def generate_python_project(project_path: Path, name: str) -> int:
    """Generate a Python MCP server project."""
    # Create directory structure
    src_dir = project_path / name.replace("-", "_")
    src_dir.mkdir()
    
    # Create main server file
    server_file = src_dir / "server.py"
    with open(server_file, 'w') as f:
        f.write(PYTHON_TEMPLATE.format(name=name))
    
    # Create __init__.py
    init_file = src_dir / "__init__.py"
    with open(init_file, 'w') as f:
        f.write(f'"""{name} MCP Server"""\n')
    
    # Create requirements.txt
    req_file = project_path / "requirements.txt"
    with open(req_file, 'w') as f:
        f.write(PYTHON_REQUIREMENTS)
    
    # Create pyproject.toml
    pyproject_file = project_path / "pyproject.toml"
    with open(pyproject_file, 'w') as f:
        f.write(PYTHON_PYPROJECT.format(
            name=name,
            module_name=name.replace("-", "_")
        ))
    
    # Create README.md
    readme_file = project_path / "README.md"
    with open(readme_file, 'w') as f:
        f.write(generate_readme(name, "python"))
    
    # Create mcpforge.json
    mcpforge_file = project_path / "mcpforge.json"
    with open(mcpforge_file, 'w') as f:
        json.dump({
            "name": name,
            "version": "0.1.0",
            "type": "mcp-server",
            "template": "python",
            "entry": f"{name.replace('-', '_')}.server:main"
        }, f, indent=2)
    
    print_success(f"Created Python MCP server project: {name}")
    print()
    print("Next steps:")
    print(f"  cd {project_path.name}")
    print("  pip install -e .")
    print(f"  python -m {name.replace('-', '_')}.server")
    
    return 0


def generate_typescript_project(project_path: Path, name: str) -> int:
    """Generate a TypeScript MCP server project."""
    # Create directory structure
    src_dir = project_path / "src"
    src_dir.mkdir()
    
    # Create main server file
    server_file = src_dir / "index.ts"
    with open(server_file, 'w') as f:
        f.write(TYPESCRIPT_TEMPLATE.format(name=name))
    
    # Create package.json
    pkg_file = project_path / "package.json"
    with open(pkg_file, 'w') as f:
        f.write(TYPESCRIPT_PACKAGE_JSON.format(name=name))
    
    # Create tsconfig.json
    tsconfig_file = project_path / "tsconfig.json"
    with open(tsconfig_file, 'w') as f:
        f.write(TYPESCRIPT_CONFIG)
    
    # Create README.md
    readme_file = project_path / "README.md"
    with open(readme_file, 'w') as f:
        f.write(generate_readme(name, "typescript"))
    
    # Create mcpforge.json
    mcpforge_file = project_path / "mcpforge.json"
    with open(mcpforge_file, 'w') as f:
        json.dump({
            "name": name,
            "version": "0.1.0",
            "type": "mcp-server",
            "template": "typescript",
            "entry": "dist/index.js"
        }, f, indent=2)
    
    print_success(f"Created TypeScript MCP server project: {name}")
    print()
    print("Next steps:")
    print(f"  cd {project_path.name}")
    print("  npm install")
    print("  npm run build")
    print("  npm start")
    
    return 0


def generate_readme(name: str, template: str) -> str:
    """Generate a README.md file."""
    return f"""# {name}

MCP Server generated by MCPForge

## Description

This is a Model Context Protocol (MCP) server generated using the `{template}` template.

## Installation

### Development

```bash
# Install dependencies
{"pip install -e ." if template == "python" else "npm install"}

# Run the server
{"python -m " + name.replace("-", "_") + ".server" if template == "python" else "npm start"}
```

## Tools

- `example_tool`: An example tool that processes a message

## Resources

- `greeting://{{name}}`: A greeting resource

## Prompts

- `example_prompt`: An example prompt template

## License

MIT
"""
